packages:
  - "pkg/*"

overrides:
  "@types/react": "18.3.28"

onlyBuiltDependencies:
  - "@firebase/util"
  - esbuild
  - protobufjs

allowBuilds:
  "@firebase/util": true
  esbuild: true
  protobufjs: true
