export const images = {"rules-of-the-road/vehicleControls.png": {
        width: 384,
        height: 315,
        source: require('./rules-of-the-road/vehicleControls.png'),
    },"rules-of-the-road/drivers_overview.png": {
        width: 300,
        height: 169,
        source: require('./rules-of-the-road/drivers_overview.png'),
    },"rules-of-the-road/drivers_switching.png": {
        width: 301,
        height: 137,
        source: require('./rules-of-the-road/drivers_switching.png'),
    },"rules-of-the-road/drivers_simulator_anatomy.png": {
        width: 300,
        height: 267,
        source: require('./rules-of-the-road/drivers_simulator_anatomy.png'),
    },"rules-of-the-road/drivers_resolution.png": {
        width: 300,
        height: 337,
        source: require('./rules-of-the-road/drivers_resolution.png'),
    },"rules-of-the-road/drivers_settings.png": {
        width: 300,
        height: 44,
        source: require('./rules-of-the-road/drivers_settings.png'),
    },"rules-of-the-road/drivers_logbook.png": {
        width: 300,
        height: 227,
        source: require('./rules-of-the-road/drivers_logbook.png'),
    },"road-signs/GM1.2.gif": {
        width: 147,
        height: 214,
        source: require('./road-signs/GM1.2.gif'),
    },"road-signs/GM2.gif": {
        width: 256,
        height: 256,
        source: require('./road-signs/GM2.gif'),
    },"road-signs/GM3.1.gif": {
        width: 72,
        height: 180,
        source: require('./road-signs/GM3.1.gif'),
    },"road-signs/GM4.1.gif": {
        width: 73,
        height: 155,
        source: require('./road-signs/GM4.1.gif'),
    },"road-signs/GM5.gif": {
        width: 273,
        height: 139,
        source: require('./road-signs/GM5.gif'),
    },"road-signs/GM6.2.gif": {
        width: 108,
        height: 194,
        source: require('./road-signs/GM6.2.gif'),
    },"road-signs/GM7.1.gif": {
        width: 187,
        height: 236,
        source: require('./road-signs/GM7.1.gif'),
    },"road-signs/GM8.gif": {
        width: 170,
        height: 17,
        source: require('./road-signs/GM8.gif'),
    },"road-signs/RM1.gif": {
        width: 78,
        height: 192,
        source: require('./road-signs/RM1.gif'),
    },"road-signs/RM2.1.gif": {
        width: 83,
        height: 192,
        source: require('./road-signs/RM2.1.gif'),
    },"road-signs/RM3.gif": {
        width: 78,
        height: 192,
        source: require('./road-signs/RM3.gif'),
    },"road-signs/RM4.1.gif": {
        width: 106,
        height: 192,
        source: require('./road-signs/RM4.1.gif'),
    },"road-signs/RM4.2.gif": {
        width: 106,
        height: 192,
        source: require('./road-signs/RM4.2.gif'),
    },"road-signs/RM5.2.gif": {
        width: 166,
        height: 214,
        source: require('./road-signs/RM5.2.gif'),
    },"road-signs/RM6.gif": {
        width: 161,
        height: 207,
        source: require('./road-signs/RM6.gif'),
    },"road-signs/RM7.gif": {
        width: 142,
        height: 206,
        source: require('./road-signs/RM7.gif'),
    },"road-signs/RM8.gif": {
        width: 248,
        height: 167,
        source: require('./road-signs/RM8.gif'),
    },"road-signs/RM9.gif": {
        width: 143,
        height: 248,
        source: require('./road-signs/RM9.gif'),
    },"road-signs/RM17.1.gif": {
        width: 108,
        height: 194,
        source: require('./road-signs/RM17.1.gif'),
    },"road-signs/RM10.gif": {
        width: 143,
        height: 248,
        source: require('./road-signs/RM10.gif'),
    },"road-signs/RM11.gif": {
        width: 182,
        height: 274,
        source: require('./road-signs/RM11.gif'),
    },"road-signs/RM12.1.gif": {
        width: 123,
        height: 207,
        source: require('./road-signs/RM12.1.gif'),
    },"road-signs/RM13.1.gif": {
        width: 123,
        height: 207,
        source: require('./road-signs/RM13.1.gif'),
    },"road-signs/RM14.gif": {
        width: 248,
        height: 138,
        source: require('./road-signs/RM14.gif'),
    },"road-signs/RM15.gif": {
        width: 227,
        height: 227,
        source: require('./road-signs/RM15.gif'),
    },"road-signs/RM16.gif": {
        width: 240,
        height: 136,
        source: require('./road-signs/RM16.gif'),
    },"road-signs/RTM1.gif": {
        width: 146,
        height: 214,
        source: require('./road-signs/RTM1.gif'),
    },"road-signs/RTM2.gif": {
        width: 126,
        height: 192,
        source: require('./road-signs/RTM2.gif'),
    },"road-signs/RTM3.gif": {
        width: 214,
        height: 166,
        source: require('./road-signs/RTM3.gif'),
    },"road-signs/RTM4.gif": {
        width: 192,
        height: 146,
        source: require('./road-signs/RTM4.gif'),
    },"road-signs/WM1.gif": {
        width: 116,
        height: 231,
        source: require('./road-signs/WM1.gif'),
    },"road-signs/WM2.3.gif": {
        width: 90,
        height: 214,
        source: require('./road-signs/WM2.3.gif'),
    },"road-signs/WM3.2.gif": {
        width: 97,
        height: 214,
        source: require('./road-signs/WM3.2.gif'),
    },"road-signs/WM4.gif": {
        width: 98,
        height: 214,
        source: require('./road-signs/WM4.gif'),
    },"road-signs/WM5.gif": {
        width: 116,
        height: 232,
        source: require('./road-signs/WM5.gif'),
    },"road-signs/WM6.gif": {
        width: 292,
        height: 127,
        source: require('./road-signs/WM6.gif'),
    },"road-signs/WM7.gif": {
        width: 257,
        height: 173,
        source: require('./road-signs/WM7.gif'),
    },"road-signs/WM8.gif": {
        width: 235,
        height: 148,
        source: require('./road-signs/WM8.gif'),
    },"road-signs/WM9.1.gif": {
        width: 275,
        height: 189,
        source: require('./road-signs/WM9.1.gif'),
    },"road-signs/WM9.2.gif": {
        width: 275,
        height: 189,
        source: require('./road-signs/WM9.2.gif'),
    },"road-signs/WM10.gif": {
        width: 187,
        height: 235,
        source: require('./road-signs/WM10.gif'),
    },"road-signs/WM11.2.gif": {
        width: 187,
        height: 235,
        source: require('./road-signs/WM11.2.gif'),
    },"road-signs/SS2A.gif": {
        width: 152,
        height: 153,
        source: require('./road-signs/SS2A.gif'),
    },"road-signs/SS2B.gif": {
        width: 75,
        height: 135,
        source: require('./road-signs/SS2B.gif'),
    },"road-signs/SS1A.gif": {
        width: 44,
        height: 149,
        source: require('./road-signs/SS1A.gif'),
    },"road-signs/SS1B.gif": {
        width: 74,
        height: 142,
        source: require('./road-signs/SS1B.gif'),
    },"road-signs/SS1C.gif": {
        width: 76,
        height: 148,
        source: require('./road-signs/SS1C.gif'),
    },"road-signs/SS1D.gif": {
        width: 37,
        height: 149,
        source: require('./road-signs/SS1D.gif'),
    },"road-signs/S16.gif": {
        width: 121,
        height: 141,
        source: require('./road-signs/S16.gif'),
    },"road-signs/S17.gif": {
        width: 121,
        height: 141,
        source: require('./road-signs/S17.gif'),
    },"road-signs/S18.gif": {
        width: 121,
        height: 141,
        source: require('./road-signs/S18.gif'),
    },"road-signs/S19.gif": {
        width: 121,
        height: 141,
        source: require('./road-signs/S19.gif'),
    },"road-signs/FRD.gif": {
        width: 63,
        height: 149,
        source: require('./road-signs/FRD.gif'),
    },"road-signs/FRD-R1.gif": {
        width: 80,
        height: 150,
        source: require('./road-signs/FRD-R1.gif'),
    },"road-signs/S11.gif": {
        width: 42,
        height: 83,
        source: require('./road-signs/S11.gif'),
    },"road-signs/S1.gif": {
        width: 64,
        height: 143,
        source: require('./road-signs/S1.gif'),
    },"road-signs/S1B.gif": {
        width: 63,
        height: 144,
        source: require('./road-signs/S1B.gif'),
    },"road-signs/S1T.gif": {
        width: 63,
        height: 144,
        source: require('./road-signs/S1T.gif'),
    },"road-signs/S8B.gif": {
        width: 103,
        height: 144,
        source: require('./road-signs/S8B.gif'),
    },"road-signs/S8T.gif": {
        width: 104,
        height: 144,
        source: require('./road-signs/S8T.gif'),
    },"road-signs/S1AL.gif": {
        width: 63,
        height: 144,
        source: require('./road-signs/S1AL.gif'),
    },"road-signs/S1L.gif": {
        width: 103,
        height: 144,
        source: require('./road-signs/S1L.gif'),
    },"road-signs/S9.gif": {
        width: 104,
        height: 144,
        source: require('./road-signs/S9.gif'),
    },"road-signs/SS4A.gif": {
        width: 134,
        height: 135,
        source: require('./road-signs/SS4A.gif'),
    },"road-signs/GS501.gif": {
        width: 120,
        height: 150,
        source: require('./road-signs/GS501.gif'),
    },"road-signs/GS505.gif": {
        width: 113,
        height: 150,
        source: require('./road-signs/GS505.gif'),
    },"road-signs/GS103.gif": {
        width: 113,
        height: 150,
        source: require('./road-signs/GS103.gif'),
    },"road-signs/GS205.gif": {
        width: 113,
        height: 150,
        source: require('./road-signs/GS205.gif'),
    },"road-signs/GS302.gif": {
        width: 113,
        height: 150,
        source: require('./road-signs/GS302.gif'),
    },"road-signs/GS403.gif": {
        width: 141,
        height: 150,
        source: require('./road-signs/GS403.gif'),
    },"road-signs/GS605.gif": {
        width: 103,
        height: 136,
        source: require('./road-signs/GS605.gif'),
    },"road-signs/GS701.gif": {
        width: 136,
        height: 137,
        source: require('./road-signs/GS701.gif'),
    },"road-signs/GS818.gif": {
        width: 128,
        height: 137,
        source: require('./road-signs/GS818.gif'),
    },"road-signs/GS901.gif": {
        width: 103,
        height: 137,
        source: require('./road-signs/GS901.gif'),
    },"road-signs/GD2.gif": {
        width: 385,
        height: 242,
        source: require('./road-signs/GD2.gif'),
    },"road-signs/GD3.gif": {
        width: 372,
        height: 135,
        source: require('./road-signs/GD3.gif'),
    },"road-signs/GD4.gif": {
        width: 285,
        height: 98,
        source: require('./road-signs/GD4.gif'),
    },"road-signs/GA2.gif": {
        width: 194,
        height: 141,
        source: require('./road-signs/GA2.gif'),
    },"road-signs/GA3.gif": {
        width: 264,
        height: 131,
        source: require('./road-signs/GA3.gif'),
    },"road-signs/GA4.gif": {
        width: 84,
        height: 136,
        source: require('./road-signs/GA4.gif'),
    },"road-signs/GA8.gif": {
        width: 278,
        height: 184,
        source: require('./road-signs/GA8.gif'),
    },"road-signs/GB2.gif": {
        width: 200,
        height: 43,
        source: require('./road-signs/GB2.gif'),
    },"road-signs/GB3.gif": {
        width: 225,
        height: 49,
        source: require('./road-signs/GB3.gif'),
    },"road-signs/GC1.gif": {
        width: 195,
        height: 190,
        source: require('./road-signs/GC1.gif'),
    },"road-signs/GL1.gif": {
        width: 228,
        height: 47,
        source: require('./road-signs/GL1.gif'),
    },"road-signs/GL2.gif": {
        width: 186,
        height: 46,
        source: require('./road-signs/GL2.gif'),
    },"road-signs/GL3.gif": {
        width: 158,
        height: 106,
        source: require('./road-signs/GL3.gif'),
    },"road-signs/GL4.gif": {
        width: 168,
        height: 112,
        source: require('./road-signs/GL4.gif'),
    },"road-signs/GL5.gif": {
        width: 154,
        height: 75,
        source: require('./road-signs/GL5.gif'),
    },"road-signs/GL6.gif": {
        width: 196,
        height: 105,
        source: require('./road-signs/GL6.gif'),
    },"road-signs/GL7.gif": {
        width: 242,
        height: 105,
        source: require('./road-signs/GL7.gif'),
    },"road-signs/GL8.gif": {
        width: 177,
        height: 105,
        source: require('./road-signs/GL8.gif'),
    },"road-signs/GE9.gif": {
        width: 75,
        height: 112,
        source: require('./road-signs/GE9.gif'),
    },"road-signs/GE2.gif": {
        width: 131,
        height: 165,
        source: require('./road-signs/GE2.gif'),
    },"road-signs/GE18.3.gif": {
        width: 156,
        height: 103,
        source: require('./road-signs/GE18.3.gif'),
    },"road-signs/GE19.3.gif": {
        width: 203,
        height: 103,
        source: require('./road-signs/GE19.3.gif'),
    },"road-signs/GF1.gif": {
        width: 320,
        height: 165,
        source: require('./road-signs/GF1.gif'),
    },"road-signs/GF2.gif": {
        width: 337,
        height: 67,
        source: require('./road-signs/GF2.gif'),
    },"road-signs/GF3.gif": {
        width: 220,
        height: 67,
        source: require('./road-signs/GF3.gif'),
    },"road-signs/GF8.gif": {
        width: 259,
        height: 180,
        source: require('./road-signs/GF8.gif'),
    },"road-signs/GF9.gif": {
        width: 282,
        height: 179,
        source: require('./road-signs/GF9.gif'),
    },"road-signs/GF12.gif": {
        width: 130,
        height: 174,
        source: require('./road-signs/GF12.gif'),
    },"road-signs/GFS-D1-18.gif": {
        width: 53,
        height: 52,
        source: require('./road-signs/GFS-D1-18.gif'),
    },"road-signs/GFS-D1-22.gif": {
        width: 53,
        height: 52,
        source: require('./road-signs/GFS-D1-22.gif'),
    },"road-signs/GFS-B1-2-RSA.gif": {
        width: 62,
        height: 61,
        source: require('./road-signs/GFS-B1-2-RSA.gif'),
    },"road-signs/IN3.gif": {
        width: 61,
        height: 104,
        source: require('./road-signs/IN3.gif'),
    },"road-signs/IN2.gif": {
        width: 61,
        height: 104,
        source: require('./road-signs/IN2.gif'),
    },"road-signs/IN1.gif": {
        width: 61,
        height: 104,
        source: require('./road-signs/IN1.gif'),
    },"road-signs/IN4.gif": {
        width: 79,
        height: 106,
        source: require('./road-signs/IN4.gif'),
    },"road-signs/IN5.gif": {
        width: 80,
        height: 106,
        source: require('./road-signs/IN5.gif'),
    },"road-signs/IN6.gif": {
        width: 80,
        height: 106,
        source: require('./road-signs/IN6.gif'),
    },"road-signs/IN7.gif": {
        width: 149,
        height: 149,
        source: require('./road-signs/IN7.gif'),
    },"road-signs/IN10.gif": {
        width: 149,
        height: 112,
        source: require('./road-signs/IN10.gif'),
    },"road-signs/IN11.1.gif": {
        width: 135,
        height: 36,
        source: require('./road-signs/IN11.1.gif'),
    },"road-signs/IN12.gif": {
        width: 84,
        height: 112,
        source: require('./road-signs/IN12.gif'),
    },"road-signs/IN14.gif": {
        width: 112,
        height: 149,
        source: require('./road-signs/IN14.gif'),
    },"road-signs/IN15.gif": {
        width: 112,
        height: 122,
        source: require('./road-signs/IN15.gif'),
    },"road-signs/IN19.gif": {
        width: 149,
        height: 112,
        source: require('./road-signs/IN19.gif'),
    },"road-signs/IN25.gif": {
        width: 229,
        height: 166,
        source: require('./road-signs/IN25.gif'),
    },"road-signs/R101.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R101.gif'),
    },"road-signs/R102.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R102.gif'),
    },"road-signs/R103.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R103.gif'),
    },"road-signs/R104.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R104.gif'),
    },"road-signs/R105.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R105.gif'),
    },"road-signs/R106.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R106.gif'),
    },"road-signs/R107.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R107.gif'),
    },"road-signs/R108.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R108.gif'),
    },"road-signs/R109.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R109.gif'),
    },"road-signs/R110.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R110.gif'),
    },"road-signs/R111.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R111.gif'),
    },"road-signs/R112.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R112.gif'),
    },"road-signs/R113.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R113.gif'),
    },"road-signs/R114.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R114.gif'),
    },"road-signs/R115.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R115.gif'),
    },"road-signs/R116.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R116.gif'),
    },"road-signs/R117.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R117.gif'),
    },"road-signs/R118.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R118.gif'),
    },"road-signs/R119.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R119.gif'),
    },"road-signs/R120.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R120.gif'),
    },"road-signs/R121.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R121.gif'),
    },"road-signs/R122.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R122.gif'),
    },"road-signs/R123.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R123.gif'),
    },"road-signs/R124.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R124.gif'),
    },"road-signs/R125.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R125.gif'),
    },"road-signs/R126.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R126.gif'),
    },"road-signs/R127.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R127.gif'),
    },"road-signs/R128.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R128.gif'),
    },"road-signs/R129.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R129.gif'),
    },"road-signs/R130.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R130.gif'),
    },"road-signs/R131.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R131.gif'),
    },"road-signs/R132.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R132.gif'),
    },"road-signs/R133.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R133.gif'),
    },"road-signs/R134.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R134.gif'),
    },"road-signs/R135.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R135.gif'),
    },"road-signs/R137.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R137.gif'),
    },"road-signs/R138.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R138.gif'),
    },"road-signs/R139.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R139.gif'),
    },"road-signs/R140.gif": {
        width: 158,
        height: 158,
        source: require('./road-signs/R140.gif'),
    },"road-signs/R401.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R401.gif'),
    },"road-signs/R402.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R402.gif'),
    },"road-signs/R403.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R403.gif'),
    },"road-signs/R1.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R1.gif'),
    },"road-signs/R1.2.gif": {
        width: 78,
        height: 165,
        source: require('./road-signs/R1.2.gif'),
    },"road-signs/R1.3.gif": {
        width: 117,
        height: 165,
        source: require('./road-signs/R1.3.gif'),
    },"road-signs/R1.4.gif": {
        width: 117,
        height: 165,
        source: require('./road-signs/R1.4.gif'),
    },"road-signs/R1.5.gif": {
        width: 70,
        height: 162,
        source: require('./road-signs/R1.5.gif'),
    },"road-signs/R2.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/R2.gif'),
    },"road-signs/R2.1.gif": {
        width: 134,
        height: 186,
        source: require('./road-signs/R2.1.gif'),
    },"road-signs/R2.2.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/R2.2.gif'),
    },"road-signs/R3.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R3.gif'),
    },"road-signs/R4.1.gif": {
        width: 88,
        height: 66,
        source: require('./road-signs/R4.1.gif'),
    },"road-signs/R5.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R5.gif'),
    },"road-signs/R6.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R6.gif'),
    },"road-signs/R600.gif": {
        width: 96,
        height: 96,
        source: require('./road-signs/R600.gif'),
    },"road-signs/R501.gif": {
        width: 117,
        height: 44,
        source: require('./road-signs/R501.gif'),
    },"road-signs/R502.gif": {
        width: 117,
        height: 70,
        source: require('./road-signs/R502.gif'),
    },"road-signs/R503.gif": {
        width: 116,
        height: 111,
        source: require('./road-signs/R503.gif'),
    },"road-signs/R505.gif": {
        width: 117,
        height: 149,
        source: require('./road-signs/R505.gif'),
    },"road-signs/R506.gif": {
        width: 117,
        height: 88,
        source: require('./road-signs/R506.gif'),
    },"road-signs/R511.gif": {
        width: 114,
        height: 86,
        source: require('./road-signs/R511.gif'),
    },"road-signs/R512.gif": {
        width: 114,
        height: 86,
        source: require('./road-signs/R512.gif'),
    },"road-signs/R523.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R523.gif'),
    },"road-signs/R532.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R532.gif'),
    },"road-signs/R533.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R533.gif'),
    },"road-signs/R534.gif": {
        width: 115,
        height: 153,
        source: require('./road-signs/R534.gif'),
    },"road-signs/R535.gif": {
        width: 115,
        height: 65,
        source: require('./road-signs/R535.gif'),
    },"road-signs/R540.gif": {
        width: 115,
        height: 87,
        source: require('./road-signs/R540.gif'),
    },"road-signs/R562.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R562.gif'),
    },"road-signs/R565.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R565.gif'),
    },"road-signs/R571.gif": {
        width: 115,
        height: 86,
        source: require('./road-signs/R571.gif'),
    },"road-signs/R201.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R201.gif'),
    },"road-signs/R202.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R202.gif'),
    },"road-signs/R203.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R203.gif'),
    },"road-signs/R204.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R204.gif'),
    },"road-signs/R205.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R205.gif'),
    },"road-signs/R206.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R206.gif'),
    },"road-signs/R207.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R207.gif'),
    },"road-signs/R208.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R208.gif'),
    },"road-signs/R209.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R209.gif'),
    },"road-signs/R210.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R210.gif'),
    },"road-signs/R211.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R211.gif'),
    },"road-signs/R212.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R212.gif'),
    },"road-signs/R213.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R213.gif'),
    },"road-signs/R214.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R214.gif'),
    },"road-signs/R215.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R215.gif'),
    },"road-signs/R216.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R216.gif'),
    },"road-signs/R217.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R217.gif'),
    },"road-signs/R218.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R218.gif'),
    },"road-signs/R219.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R219.gif'),
    },"road-signs/R220.gif": {
        width: 117,
        height: 116,
        source: require('./road-signs/R220.gif'),
    },"road-signs/R222.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R222.gif'),
    },"road-signs/R223.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R223.gif'),
    },"road-signs/R224.gif": {
        width: 116,
        height: 116,
        source: require('./road-signs/R224.gif'),
    },"road-signs/R225.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R225.gif'),
    },"road-signs/R227.gif": {
        width: 116,
        height: 117,
        source: require('./road-signs/R227.gif'),
    },"road-signs/R228.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R228.gif'),
    },"road-signs/R229.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R229.gif'),
    },"road-signs/R230.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R230.gif'),
    },"road-signs/R231.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R231.gif'),
    },"road-signs/R232.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R232.gif'),
    },"road-signs/R233.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R233.gif'),
    },"road-signs/R234.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R234.gif'),
    },"road-signs/R235.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R235.gif'),
    },"road-signs/R236.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R236.gif'),
    },"road-signs/R237.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R237.gif'),
    },"road-signs/R238.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R238.gif'),
    },"road-signs/R239.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R239.gif'),
    },"road-signs/R240.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R240.gif'),
    },"road-signs/R241.gif": {
        width: 117,
        height: 117,
        source: require('./road-signs/R241.gif'),
    },"road-signs/R302.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R302.gif'),
    },"road-signs/R303.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R303.gif'),
    },"road-signs/R304.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R304.gif'),
    },"road-signs/R307.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R307.gif'),
    },"road-signs/R308.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R308.gif'),
    },"road-signs/R309.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R309.gif'),
    },"road-signs/R310.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R310.gif'),
    },"road-signs/R311.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R311.gif'),
    },"road-signs/R312.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R312.gif'),
    },"road-signs/R313.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R313.gif'),
    },"road-signs/R314.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R314.gif'),
    },"road-signs/R315.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R315.gif'),
    },"road-signs/R316.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R316.gif'),
    },"road-signs/R317.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R317.gif'),
    },"road-signs/R318.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R318.gif'),
    },"road-signs/R319.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R319.gif'),
    },"road-signs/R320.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R320.gif'),
    },"road-signs/R321.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R321.gif'),
    },"road-signs/R322.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R322.gif'),
    },"road-signs/R323.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R323.gif'),
    },"road-signs/R324.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R324.gif'),
    },"road-signs/R325.gif": {
        width: 88,
        height: 175,
        source: require('./road-signs/R325.gif'),
    },"road-signs/R326.gif": {
        width: 88,
        height: 175,
        source: require('./road-signs/R326.gif'),
    },"road-signs/R327.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R327.gif'),
    },"road-signs/R328.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R328.gif'),
    },"road-signs/R329.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R329.gif'),
    },"road-signs/R330.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R330.gif'),
    },"road-signs/R331.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R331.gif'),
    },"road-signs/R332.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R332.gif'),
    },"road-signs/R333.gif": {
        width: 88,
        height: 144,
        source: require('./road-signs/R333.gif'),
    },"road-signs/R334.gif": {
        width: 88,
        height: 144,
        source: require('./road-signs/R334.gif'),
    },"road-signs/R335.gif": {
        width: 88,
        height: 144,
        source: require('./road-signs/R335.gif'),
    },"road-signs/R336.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R336.gif'),
    },"road-signs/R337.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R337.gif'),
    },"road-signs/R338.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R338.gif'),
    },"road-signs/R339.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R339.gif'),
    },"road-signs/R340.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R340.gif'),
    },"road-signs/R341.gif": {
        width: 88,
        height: 175,
        source: require('./road-signs/R341.gif'),
    },"road-signs/R342.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R342.gif'),
    },"road-signs/R343.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R343.gif'),
    },"road-signs/R344.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R344.gif'),
    },"road-signs/R345.gif": {
        width: 88,
        height: 148,
        source: require('./road-signs/R345.gif'),
    },"road-signs/R346.gif": {
        width: 88,
        height: 148,
        source: require('./road-signs/R346.gif'),
    },"road-signs/R347.gif": {
        width: 88,
        height: 148,
        source: require('./road-signs/R347.gif'),
    },"road-signs/R348.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R348.gif'),
    },"road-signs/R349.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R349.gif'),
    },"road-signs/R350.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R350.gif'),
    },"road-signs/R351.gif": {
        width: 88,
        height: 148,
        source: require('./road-signs/R351.gif'),
    },"road-signs/R352.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R352.gif'),
    },"road-signs/R353.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R353.gif'),
    },"road-signs/R354.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R354.gif'),
    },"road-signs/R301P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R301P.gif'),
    },"road-signs/R304P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R304P.gif'),
    },"road-signs/R305P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R305P.gif'),
    },"road-signs/R306P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R306P.gif'),
    },"road-signs/R307P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R307P.gif'),
    },"road-signs/R308P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R308P.gif'),
    },"road-signs/R309P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R309P.gif'),
    },"road-signs/R310P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R310P.gif'),
    },"road-signs/R311P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R311P.gif'),
    },"road-signs/R312P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R312P.gif'),
    },"road-signs/R313P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R313P.gif'),
    },"road-signs/R314P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R314P.gif'),
    },"road-signs/R315P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R315P.gif'),
    },"road-signs/R316P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R316P.gif'),
    },"road-signs/R317P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R317P.gif'),
    },"road-signs/R318P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R318P.gif'),
    },"road-signs/R319P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R319P.gif'),
    },"road-signs/R320P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R320P.gif'),
    },"road-signs/R321P.gif": {
        width: 88,
        height: 116,
        source: require('./road-signs/R321P.gif'),
    },"road-signs/R322P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R322P.gif'),
    },"road-signs/R323P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R323P.gif'),
    },"road-signs/R324P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R324P.gif'),
    },"road-signs/R327P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R327P.gif'),
    },"road-signs/R330P.gif": {
        width: 88,
        height: 117,
        source: require('./road-signs/R330P.gif'),
    },"road-signs/R333P.gif": {
        width: 88,
        height: 144,
        source: require('./road-signs/R333P.gif'),
    },"road-signs/W201.gif": {
        width: 134,
        height: 118,
        source: require('./road-signs/W201.gif'),
    },"road-signs/W202.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W202.gif'),
    },"road-signs/W203.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W203.gif'),
    },"road-signs/W204.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W204.gif'),
    },"road-signs/W205.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W205.gif'),
    },"road-signs/W206.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W206.gif'),
    },"road-signs/W207.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W207.gif'),
    },"road-signs/W208.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W208.gif'),
    },"road-signs/W209.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W209.gif'),
    },"road-signs/W210.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W210.gif'),
    },"road-signs/W212.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W212.gif'),
    },"road-signs/W213.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W213.gif'),
    },"road-signs/W214.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W214.gif'),
    },"road-signs/W215.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W215.gif'),
    },"road-signs/W216.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W216.gif'),
    },"road-signs/W218.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W218.gif'),
    },"road-signs/W101.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W101.gif'),
    },"road-signs/W102.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W102.gif'),
    },"road-signs/W103.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W103.gif'),
    },"road-signs/W104.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W104.gif'),
    },"road-signs/W105.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W105.gif'),
    },"road-signs/W107.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W107.gif'),
    },"road-signs/W109.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W109.gif'),
    },"road-signs/W111.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W111.gif'),
    },"road-signs/W114.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W114.gif'),
    },"road-signs/W115.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W115.gif'),
    },"road-signs/W116.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W116.gif'),
    },"road-signs/W117.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W117.gif'),
    },"road-signs/W118.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W118.gif'),
    },"road-signs/W119.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/W119.gif'),
    },"road-signs/W301.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W301.gif'),
    },"road-signs/W302.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W302.gif'),
    },"road-signs/W303.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W303.gif'),
    },"road-signs/TW304.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/TW304.gif'),
    },"road-signs/TW305.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/TW305.gif'),
    },"road-signs/W306.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W306.gif'),
    },"road-signs/W307.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W307.gif'),
    },"road-signs/W308.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W308.gif'),
    },"road-signs/W309.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W309.gif'),
    },"road-signs/W310.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W310.gif'),
    },"road-signs/W311.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W311.gif'),
    },"road-signs/W312.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W312.gif'),
    },"road-signs/W313.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W313.gif'),
    },"road-signs/W314.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W314.gif'),
    },"road-signs/W315.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W315.gif'),
    },"road-signs/W316.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W316.gif'),
    },"road-signs/W317.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W317.gif'),
    },"road-signs/W318.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W318.gif'),
    },"road-signs/W319.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W319.gif'),
    },"road-signs/W320.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W320.gif'),
    },"road-signs/W321.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W321.gif'),
    },"road-signs/W322.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W322.gif'),
    },"road-signs/W323.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W323.gif'),
    },"road-signs/W324.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W324.gif'),
    },"road-signs/W325.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W325.gif'),
    },"road-signs/W326.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W326.gif'),
    },"road-signs/W327.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W327.gif'),
    },"road-signs/W328.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W328.gif'),
    },"road-signs/W329.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W329.gif'),
    },"road-signs/W330.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W330.gif'),
    },"road-signs/W331.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W331.gif'),
    },"road-signs/W332.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W332.gif'),
    },"road-signs/W333.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W333.gif'),
    },"road-signs/W334.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W334.gif'),
    },"road-signs/W335.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W335.gif'),
    },"road-signs/TW336.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/TW336.gif'),
    },"road-signs/TW337.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/TW337.gif'),
    },"road-signs/TW338.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/TW338.gif'),
    },"road-signs/W339.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W339.gif'),
    },"road-signs/TW340.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/TW340.gif'),
    },"road-signs/TW341.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/TW341.gif'),
    },"road-signs/TW342.gif": {
        width: 133,
        height: 117,
        source: require('./road-signs/TW342.gif'),
    },"road-signs/TW343.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/TW343.gif'),
    },"road-signs/TW344.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/TW344.gif'),
    },"road-signs/TW345.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/TW345.gif'),
    },"road-signs/W346.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W346.gif'),
    },"road-signs/TW347.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/TW347.gif'),
    },"road-signs/W348.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W348.gif'),
    },"road-signs/W349.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W349.gif'),
    },"road-signs/W350.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W350.gif'),
    },"road-signs/W351.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W351.gif'),
    },"road-signs/TW353.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/TW353.gif'),
    },"road-signs/W354.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W354.gif'),
    },"road-signs/W355.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W355.gif'),
    },"road-signs/W356.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W356.gif'),
    },"road-signs/W357.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W357.gif'),
    },"road-signs/W358.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W358.gif'),
    },"road-signs/W359.gif": {
        width: 134,
        height: 116,
        source: require('./road-signs/W359.gif'),
    },"road-signs/W360.gif": {
        width: 134,
        height: 117,
        source: require('./road-signs/W360.gif'),
    },"road-signs/W361.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W361.gif'),
    },"road-signs/W362.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W362.gif'),
    },"road-signs/W363.gif": {
        width: 133,
        height: 116,
        source: require('./road-signs/W363.gif'),
    },"road-signs/W401.gif": {
        width: 30,
        height: 116,
        source: require('./road-signs/W401.gif'),
    },"road-signs/W402.gif": {
        width: 30,
        height: 116,
        source: require('./road-signs/W402.gif'),
    },"road-signs/TW401.gif": {
        width: 30,
        height: 116,
        source: require('./road-signs/TW401.gif'),
    },"road-signs/W403.gif": {
        width: 116,
        height: 67,
        source: require('./road-signs/W403.gif'),
    },"road-signs/W404.gif": {
        width: 116,
        height: 93,
        source: require('./road-signs/W404.gif'),
    },"road-signs/W405.gif": {
        width: 47,
        height: 47,
        source: require('./road-signs/W405.gif'),
    },"road-signs/W406.gif": {
        width: 47,
        height: 47,
        source: require('./road-signs/W406.gif'),
    },"road-signs/W407.gif": {
        width: 140,
        height: 47,
        source: require('./road-signs/W407.gif'),
    },"road-signs/W408.gif": {
        width: 140,
        height: 47,
        source: require('./road-signs/W408.gif'),
    },"road-signs/W409.gif": {
        width: 209,
        height: 35,
        source: require('./road-signs/W409.gif'),
    },"road-signs/W410.gif": {
        width: 210,
        height: 35,
        source: require('./road-signs/W410.gif'),
    },"road-signs/W411.gif": {
        width: 293,
        height: 35,
        source: require('./road-signs/W411.gif'),
    },"road-signs/TW411.gif": {
        width: 212,
        height: 36,
        source: require('./road-signs/TW411.gif'),
    },"road-signs/TW412.2.gif": {
        width: 108,
        height: 90,
        source: require('./road-signs/TW412.2.gif'),
    },"road-signs/W413.gif": {
        width: 68,
        height: 117,
        source: require('./road-signs/W413.gif'),
    },"road-signs/W414.gif": {
        width: 94,
        height: 47,
        source: require('./road-signs/W414.gif'),
    },"road-signs/W415.gif": {
        width: 116,
        height: 30,
        source: require('./road-signs/W415.gif'),
    },}